export const accessories = [
  {
    id: "accessory-1",
    title: "Accessory-1",
    price: "$49",
    priceInINR: "₹3,800",
    discountedPrice: "₹3,500",
    originalPrice: "₹3,900",
    discount: "10% OFF",
    rating: "4.3",
    reviewsCount: 85,
    image: "/accessories/image1 (1).webp",
    category: "accessories",
  },
  {
    id: "accessory-2",
    title: "Accessory-2",
    price: "$89",
    priceInINR: "₹6,700",
    discountedPrice: "₹6,200",
    originalPrice: "₹6,900",
    discount: "10% OFF",
    rating: "4.5",
    reviewsCount: 120,
    image: "/accessories/image1 (2).webp",
    category: "accessories",
  },
  {
    id: "accessory-3",
    title: "Accessory-3",
    price: "$19",
    priceInINR: "₹1,400",
    discountedPrice: "₹1,200",
    originalPrice: "₹1,500",
    discount: "20% OFF",
    rating: "4.2",
    reviewsCount: 60,
    image: "/accessories/image1 (3).webp",
    category: "accessories",
  },
  {
    id: "accessory-4",
    title: "Accessory-4",
    price: "$15",
    priceInINR: "₹1,100",
    discountedPrice: "₹950",
    originalPrice: "₹1,200",
    discount: "15% OFF",
    rating: "4.0",
    reviewsCount: 90,
    image: "/accessories/image1 (4).webp",
    category: "accessories",
  },
  {
    id: "accessory-5",
    title: "Accessory-5",
    price: "$59",
    priceInINR: "₹4,500",
    discountedPrice: "₹4,000",
    originalPrice: "₹4,800",
    discount: "17% OFF",
    rating: "4.6",
    reviewsCount: 150,
    image: "/accessories/image1 (5).webp",
    category: "accessories",
  },
  {
    id: "accessory-6",
    title: "Accessory-6",
    price: "$29",
    priceInINR: "₹2,200",
    discountedPrice: "₹2,000",
    originalPrice: "₹2,300",
    discount: "13% OFF",
    rating: "4.1",
    reviewsCount: 45,
    image: "/accessories/image1 (6).webp",
    category: "accessories",
  },
  {
    id: "accessory-7",
    title: "Accessory-7",
    price: "$39",
    priceInINR: "₹3,000",
    discountedPrice: "₹2,700",
    originalPrice: "₹3,200",
    discount: "15% OFF",
    rating: "4.4",
    reviewsCount: 70,
    image: "/accessories/image1 (7).webp",
    category: "accessories",
  },
  {
    id: "accessory-8",
    title: "Accessory-8",
    price: "$35",
    priceInINR: "₹2,600",
    discountedPrice: "₹2,300",
    originalPrice: "₹2,700",
    discount: "12% OFF",
    rating: "4.5",
    reviewsCount: 95,
    image: "/accessories/image1 (8).webp",
    category: "accessories",
  },
];
