export const homeAppliances = [
  {
    id: "home-appliance-1",
    title: "Home Appliance-1",
    price: "$499",
    priceInINR: "₹37,000",
    discountedPrice: "₹34,000",
    originalPrice: "₹37,500",
    discount: "10% OFF",
    rating: "4.5",
    reviewsCount: 110,
    image: "/Homeappliances/image1 (1).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-2",
    title: "Home Appliance-2",
    price: "$599",
    priceInINR: "₹45,000",
    discountedPrice: "₹42,000",
    originalPrice: "₹45,500",
    discount: "7% OFF",
    rating: "4.3",
    reviewsCount: 190,
    image: "/Homeappliances/image1 (2).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-3",
    title: "Home Appliance-3",
    price: "$299",
    priceInINR: "₹22,000",
    discountedPrice: "₹20,500",
    originalPrice: "₹22,500",
    discount: "9% OFF",
    rating: "4.6",
    reviewsCount: 220,
    image: "/Homeappliances/image1 (3).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-4",
    title: "Home Appliance-4",
    price: "$799",
    priceInINR: "₹60,000",
    discountedPrice: "₹57,000",
    originalPrice: "₹60,500",
    discount: "5% OFF",
    rating: "4.8",
    reviewsCount: 160,
    image: "/Homeappliances/image1 (4).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-5",
    title: "Home Appliance-5",
    price: "$199",
    priceInINR: "₹15,000",
    discountedPrice: "₹14,000",
    originalPrice: "₹15,500",
    discount: "10% OFF",
    rating: "4.2",
    reviewsCount: 140,
    image: "/Homeappliances/image1 (5).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-6",
    title: "Home Appliance-6",
    price: "$149",
    priceInINR: "₹11,000",
    discountedPrice: "₹10,500",
    originalPrice: "₹11,500",
    discount: "9% OFF",
    rating: "4.4",
    reviewsCount: 175,
    image: "/Homeappliances/image1 (6).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-7",
    title: "Home Appliance-7",
    price: "$999",
    priceInINR: "₹75,000",
    discountedPrice: "₹72,000",
    originalPrice: "₹75,500",
    discount: "4% OFF",
    rating: "4.6",
    reviewsCount: 200,
    image: "/Homeappliances/image1 (7).webp",
    category: "home-appliances",
  },
  {
    id: "home-appliance-8",
    title: "Home Appliance-8",
    price: "$79",
    priceInINR: "₹6,000",
    discountedPrice: "₹5,500",
    originalPrice: "₹6,200",
    discount: "7% OFF",
    rating: "4.1",
    reviewsCount: 90,
    image: "/Homeappliances/image1 (8).webp",
    category: "home-appliances",
  },
];
