export const mobiles = [
  {
    id: "mobile-1",
    title: "Mobile 1",
    price: "$499",
    priceInINR: "₹37,000",
    discountedPrice: "₹34,000",
    originalPrice: "₹37,500",
    discount: "10% OFF",
    rating: "4.5",
    reviewsCount: 120,
    image: "/mobiles/image1 (1).webp",
    category: "mobiles",
  },
  {
    id: "mobile-2",
    title: "Mobile 2",
    price: "$599",
    priceInINR: "₹45,000",
    discountedPrice: "₹42,000",
    originalPrice: "₹45,500",
    discount: "7% OFF",
    rating: "4.2",
    reviewsCount: 200,
    image: "/mobiles/image1 (2).webp",
    category: "mobiles",
  },
  {
    id: "mobile-3",
    title: "Mobile 3",
    price: "$699",
    priceInINR: "₹52,000",
    discountedPrice: "₹49,500",
    originalPrice: "₹52,500",
    discount: "5% OFF",
    rating: "4.7",
    reviewsCount: 300,
    image: "/mobiles/image1 (3).webp",
    category: "mobiles",
  },
  {
    id: "mobile-4",
    title: "Mobile 4",
    price: "$799",
    priceInINR: "₹60,000",
    discountedPrice: "₹57,000",
    originalPrice: "₹60,500",
    discount: "5% OFF",
    rating: "4.8",
    reviewsCount: 150,
    image: "/mobiles/image1 (4).webp",
    category: "mobiles",
  },
  {
    id: "mobile-5",
    title: "Mobile 5",
    price: "$899",
    priceInINR: "₹67,000",
    discountedPrice: "₹64,000",
    originalPrice: "₹67,500",
    discount: "5% OFF",
    rating: "4.3",
    reviewsCount: 180,
    image: "/mobiles/image1 (5).webp",
    category: "mobiles",
  },
  {
    id: "mobile-6",
    title: "Mobile 6",
    price: "$999",
    priceInINR: "₹75,000",
    discountedPrice: "₹72,000",
    originalPrice: "₹75,500",
    discount: "4% OFF",
    rating: "4.6",
    reviewsCount: 250,
    image: "/mobiles/image1 (6).webp",
    category: "mobiles",
  },
  {
    id: "mobile-7",
    title: "Mobile 7",
    price: "$1099",
    priceInINR: "₹82,000",
    discountedPrice: "₹79,000",
    originalPrice: "₹82,500",
    discount: "4% OFF",
    rating: "4.4",
    reviewsCount: 320,
    image: "/mobiles/image1 (7).webp",
    category: "mobiles",
  },
  {
    id: "mobile-8",
    title: "Mobile 8",
    price: "$1199",
    priceInINR: "₹90,000",
    discountedPrice: "₹86,000",
    originalPrice: "₹90,500",
    discount: "5% OFF",
    rating: "4.7",
    reviewsCount: 400,
    image: "/mobiles/image1 (8).webp",
    category: "mobiles",
  },
];
