export const watches = [
  {
    id: "watch-1",
    title: "Watch 1",
    price: "$499",
    priceInINR: "₹4,500",
    discountedPrice: "₹4,200",
    originalPrice: "₹4,500",
    discount: "7% OFF",
    rating: "4.3",
    reviewsCount: 120,
    image: "/watches/image1 (1).webp",
    category: "Watch",
  },
  {
    id: "watch-2",
    title: "Watch 2",
    price: "$599",
    priceInINR: "₹5,600",
    discountedPrice: "₹5,400",
    originalPrice: "₹5,700",
    discount: "5% OFF",
    rating: "4.7",
    reviewsCount: 250,
    image: "/watches/image1 (2).webp",
    category: "Watch",
  },
  {
    id: "watch-3",
    title: "Watch 3",
    price: "$299",
    priceInINR: "₹6,500",
    discountedPrice: "₹6,100",
    originalPrice: "₹6,500",
    discount: "6% OFF",
    rating: "4.5",
    reviewsCount: 320,
    image: "/watches/image1 (3).webp",
    category: "Watch",
  },
  {
    id: "watch-4",
    title: "Watch 4",
    price: "$799",
    priceInINR: "₹7,800",
    discountedPrice: "₹7,200",
    originalPrice: "₹8,000",
    discount: "10% OFF",
    rating: "4.8",
    reviewsCount: 400,
    image: "/watches/image1 (4).webp",
    category: "Watch",
  },
  {
    id: "watch-5",
    title: "Watch 5",
    price: "$199",
    priceInINR: "₹8,500",
    discountedPrice: "₹8,000",
    originalPrice: "₹8,500",
    discount: "6% OFF",
    rating: "4.6",
    reviewsCount: 150,
    image: "/watches/image1 (5).webp",
    category: "Watch",
  },
  {
    id: "watch-6",
    title: "Watch 6",
    price: "$149",
    priceInINR: "₹9,000",
    discountedPrice: "₹8,500",
    originalPrice: "₹9,200",
    discount: "8% OFF",
    rating: "4.7",
    reviewsCount: 290,
    image: "/watches/image1 (14).webp",
    category: "Watch",
  },
  {
    id: "watch-7",
    title: "Watch 7",
    price: "$999",
    priceInINR: "₹10,500",
    discountedPrice: "₹9,800",
    originalPrice: "₹10,500",
    discount: "7% OFF",
    rating: "4.4",
    reviewsCount: 180,
    image: "/watches/image1 (16).webp",
    category: "Watch",
  },
  {
    id: "watch-8",
    title: "Watch 8",
    price: "$799",
    priceInINR: "₹11,500",
    discountedPrice: "₹11,000",
    originalPrice: "₹12,000",
    discount: "8% OFF",
    rating: "4.6",
    reviewsCount: 220,
    image: "/watches/image1 (8).webp",
    category: "Watch",
  },
  {
    id: "watch-9",
    title: "Watch 9",
    price: "$799",
    priceInINR: "₹12,500",
    discountedPrice: "₹11,800",
    originalPrice: "₹12,500",
    discount: "5% OFF",
    rating: "4.2",
    reviewsCount: 160,
    image: "/watches/image1 (9).webp",
    category: "Watch",
  },
  {
    id: "watch-10",
    title: "Watch 10",
    price: "$799",
    priceInINR: "₹13,500",
    discountedPrice: "₹12,900",
    originalPrice: "₹13,500",
    discount: "5% OFF",
    rating: "4.7",
    reviewsCount: 270,
    image: "/watches/image1 (10).webp",
    category: "Watch",
  },
];
